### PR TITLE
nix 2

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by prolic** [comment]
@endgame still no success with this one. cannot find glew, no matter how I try to add it. Shouldn't it be able to find it, since I did `nix-env -iA nixpkgs.glew` and it should be there already? I don't quite understand nix very well, sorry.

**Comment by endgame** [comment]
This PR adds SDL and GLEW as inputs to your flake, but your nix code doesn't do anything with them. And it shouldn't: the cryptic error you get from `haskell.nix` is saying that it doesn't know what nixpkgs package provides `GLEW`. See https://github.com/input-output-hk/haskell.nix/blob/master/docs/tutorials/pkg-map.md#mapping-in-haskellnix - you probably want to PR `haskell.nix` itself, adding `GLEW = [ glew ];` to `system-nixpkgs-map.nix`.

While you are waiting for your PR to merge, you can point this flake at your fork by changing the `haskell.nix` input to `"github:prolic/haskell.nix/name_of_your_pr_branch"`.

Whatever you've added to your local environment is going to be pretty much invisible to your `nix develop`/`nix build` calls, because how else would you get Nix's promised reproducibility?

**Comment by prolic** [comment]
Also found this one https://github.com/nim-nix-pkgs/glew - but not sure how to use.

**Comment by prolic** [comment]
ah, this one https://github.com/input-output-hk/haskell.nix/pull/1534 seems more promising. it's downloading something now.

**Comment by prolic** [comment]
build failed with:
```bash
error: builder for '/nix/store/5d9nljyh7b1l1k0z87sxsrc2llcl3rsn-cdparanoia-III-x86_64-unknown-linux-musl-10.2.drv' failed with exit code 1;
       last 10 log lines:
       > Hunk #39 succeeded at 1626 (offset 4 lines).
       > Hunk #40 succeeded at 1674 (offset 4 lines).
       > Hunk #41 succeeded at 1743 (offset 17 lines).
       > patching file interface/test_interface.c
       > updateAutotoolsGnuConfigScriptsPhase
       > configuring
       > configure flags: --prefix=/nix/store/ds2ris4kr6icprr3d7wrmy9jfg9w41k0-cdparanoia-III-x86_64-unknown-linux-musl-10.2 --build=x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-musl
       > checking build system type... x86_64-unknown-linux-gnu
       > checking host system type... Invalid configuration `x86_64-unknown-linux-musl': machine `x86_64-unknown-linux' not recognized
       > configure: error: /nix/store/dndi916j6yxzfzzj2sma2llhrlwahq06-bash-5.1-p16/bin/bash ./config.sub x86_64-unknown-linux-musl failed
       For full logs, run 'nix log /nix/store/5d9nljyh7b1l1k0z87sxsrc2llcl3rsn-cdparanoia-III-x86_64-unknown-linux-musl-10.2.drv'.
error: 1 dependencies of derivation '/nix/store/gx0zgihqg15n4m5a1cxcfpdcsh913i15-gst-plugins-base-x86_64-unknown-linux-musl-1.20.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1llwkwdfdszdkj1ksa3z3x1hxd93np6m-pipewire-x86_64-unknown-linux-musl-0.3.48.drv' failed to build
error: 1 dependencies of derivation '/nix/store/sl0f4hflj1q99mlhnj8c9256wnkngc54-SDL2-x86_64-unknown-linux-musl-2.0.20.drv' failed to build
error: 1 dependencies of derivation '/nix/store/48ygxvbfn2gnfkd0crvd2ldzn6fwgpl3-sdl2-lib-sdl2-x86_64-unknown-linux-musl-2.5.3.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/lx4qjm9mdw44v3030bbgn4mi46ck0k2c-x86_64-unknown-linux-musl-sdl2-lib-sdl2-2.5.3.3-config.drv' failed to build
error: 1 dependencies of derivation '/nix/store/m3kz0jzgk3bnsbfaxapq1i69bi5jf104-monomer-lib-monomer-x86_64-unknown-linux-musl-1.4.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8za7f887pbqifrrj7kzw0gnvxb15x0kp-x86_64-unknown-linux-musl-monomer-lib-monomer-1.4.1.0-config.drv' failed to build
error: 1 dependencies of derivation '/nix/store/waci47h76ix65h49fd4ap29q913aypgs-futr-exe-futr-x86_64-unknown-linux-musl-0.1.0.0.drv' failed to build
nix build  168,99s user 28,92s system 11% cpu 29:38,80 total
```

**Pull request closed without merging**
